---
- name: Debug available hosts and groups
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display all available hosts and groups
      debug:
        msg: "Available host: {{ inventory_hostname }} in groups {{ group_names }}"

- name: Install Web Server
  hosts: server
  gather_facts: yes
  tasks:
    - name: Debug remote user
      debug:
        msg: "Remote user is {{ ansible_user }}"

    - name: Ensure Ansible temporary directory exists
      file:
        path: "/home/runner/.ansible/tmp"
        state: directory
        mode: '0700'
      # Убираем become: yes, оставляем права для runner

    - name: Check user identity
      command: whoami
      # Убираем become: yes, проверяем текущего пользователя

    - name: Include server role
      include_role:
        name: server

- name: Configure Database
  hosts: db
  gather_facts: yes
  tasks:
    - name: Debug database configuration
      debug:
        msg: "Configuring database on {{ inventory_hostname }}"

    - name: Include db role
      include_role:
        name: db