---
- name: Debug available hosts and groups
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display all available hosts and groups
      debug:
        msg: "Available host: {{ inventory_hostname }} in groups {{ group_names }}"

- name: Configure Database
  hosts: db
  gather_facts: yes
  become: yes
  environment:
    DB_HOST: "{{ lookup('env', 'DB_HOST') }}"
    DB_NAME: "{{ lookup('env', 'DB_NAME') }}"
    DB_USER: "{{ lookup('env', 'DB_USER') }}"
    DB_PASS: "{{ lookup('env', 'DB_PASS') }}"
  tasks:
    - name: Debug database configuration
      debug:
        msg: "Configuring database on {{ inventory_hostname }}"

    - name: Include db role
      include_role:
        name: db

- name: Install Web Server
  hosts: server
  gather_facts: yes
  become: yes
  tasks:
    - name: Debug remote user
      debug:
        msg: "Remote user is {{ ansible_env.USER }}"

    - name: Ensure Ansible temporary directory exists
      file:
        path: "/home/runner/.ansible/tmp"
        state: directory
        mode: '0700'

    - name: Check user identity
      command: whoami

    - name: Include server role
      include_role:
        name: server

