---
- name: Install PostgreSQL packages
  become: true
  ansible.builtin.apt:
    name:
      - postgresql
      - python3-psycopg2
    state: present
    update_cache: true

- name: Ensure PostgreSQL is started and enabled
  become: true
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Check PostgreSQL connection
  become: true
  community.postgresql.postgresql_ping:
    login_user: postgres
  register: postgresql_status
  ignore_errors: true  # Don't fail immediately if it's not up yet

- name: Debug PostgreSQL status
  ansible.builtin.debug:
    var: postgresql_status

- name: Temporarily set postgres user authentication to trust (local only)
  become: true
  become_user: postgres
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres\s+peer'
    line: 'local   all             postgres                                  trust'
    state: present
  notify: Restart postgresql
  when: ansible_connection == 'local'

- name: Create Ansible PostgreSQL user
  become: true
  community.postgresql.postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: ALL
    state: present
  when: ansible_connection == 'local'

- name: Restore postgres user authentication to md5 (local only)
  become: true
  become_user: postgres
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres\s+trust'
    line: 'local all postgres md5'
    state: present
  notify: Restart postgresql
  when: ansible_connection == 'local'

- name: Create database
  become: true
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    state: present
  when: ansible_connection == 'local'

- name: Add host-based access for db_user
  become: true
  become_user: postgres
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    line: "host all {{ db_user }} 127.0.0.1/32 md5"
  notify: Restart postgresql