---
- name: Remove existing Laravel directory
  file:
    path: "/var/www/html"
    state: absent
    
- name: Clone Laravel repository
  git:
    repo: "https://github.com/Practical-DevOps/app-for-devops.git"
    dest: "/var/www/html"
    version: main
    force: yes
  notify: Restart Apache

- name: Install PHP dependencies with Composer
  composer:
    command: install
    working_dir: /var/www/html

- name: Install Node.js dependencies with npm
  command: npm install
  args:
    chdir: /var/www/html

- name: Build frontend assets with npm
  command: npm run build
  args:
    chdir: /var/www/html

- name: Create `.env` file
  template:
    src: ".env.j2"
    dest: "/var/www/html/.env"
  notify: Restart Apache

- name: Generate Laravel application key
  command: php artisan key:generate
  args:
    chdir: /var/www/html

- name: Run Laravel database migrations
  command: php artisan migrate --force
  args:
    chdir: /var/www/html