---
- name: Create temporary directory for Ansible
  file:
    path: /tmp/ansible
    state: directory
    mode: '0777'

- name: Set Ansible remote temporary directory
  set_fact:
    ansible_remote_tmp: /tmp/ansible

- name: Ensure the Laravel directory exists
  become: yes
  become_user: root
  file:
    path: /var/www/laravel
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Remove existing Laravel directory
  become: yes
  become_user: root
  file:
    path: "/var/www/html"
    state: absent
    
- name: Clone Laravel repository
  become: yes
  become_user: www-data
  git:
    repo: "https://github.com/Practical-DevOps/app-for-devops.git"
    dest: "/var/www/html"
    version: main
    force: yes
  notify: Restart Apache

- name: Install PHP dependencies with Composer
  become: yes
  become_user: www-data
  ansible.builtin.command: composer install
  args:
    chdir: /var/www/laravel

- name: Install Node.js dependencies with npm
  command: npm install
  args:
    chdir: /var/www/html

- name: Build frontend assets with npm
  command: npm run build
  args:
    chdir: /var/www/html

- name: Create `.env` file
  template:
    src: ".env.j2"
    dest: "/var/www/html/.env"
  notify: Restart Apache

- name: Generate Laravel application key
  command: php artisan key:generate
  args:
    chdir: /var/www/html

- name: Run Laravel database migrations
  command: php artisan migrate --force
  args:
    chdir: /var/www/html